pack: buffalo_sc
device: cpu
det_size: [320, 320]
threshold: 0.36

paths:
  facebank_dir: data/facebank
  index_path:   outputs/facebank.index
  labels_path:  outputs/labels.json

  library_dir:   data/library
  library_index: outputs/library.index
  library_meta:  outputs/library_meta.json

library:
  min_det_score: 0.5    
  min_face_size: 48     
  show_progress: true  
